// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kwdms/app/patient/internal/biz"
	"kwdms/app/patient/internal/conf"
	"kwdms/app/patient/internal/data"
	"kwdms/app/patient/internal/server"
	"kwdms/app/patient/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	patientRepo := data.NewPatientRepo(dataData, logger)
	patientUseCase := biz.NewPatientUseCase(patientRepo, logger)
	patientService := service.NewPatientService(patientUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, patientService, logger)
	grpcServer := server.NewGRPCServer(confServer, patientService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
